### ISSUE TITLE
uart buffering

### ISSUE THREAD

**Issue by jps-aldridge** [adafruit/Adafruit_CircuitPython_BNO08x_RVC#1] opened 2020-12-16 00:39 UTC
I'm using the BNO085 on a Raspberry Pi in RVC mode. I had some odd behaviour when using the example program from the Adafruit website to read the sensor in a loop every 0.1 seconds. The problem seems to be that the serial.Serial object buffers input, with the result that loop like 

    while True:
        yaw, pitch, roll, x_accel, y_accel, z_accel = rvc.heading
        print(yaw, pitch, roll, x_accel, y_accel, z_accel)
        time.sleep(0.1)

returns lots of old buffered values, rather than the current value each time it is requested. I worked round the issue by inserting a line

    rvc._uart.reset_input_buffer()

before reading the heading property, but presumably this shouldn't be necessary.

**Comment by rdagger** [comment] 2022-01-08 18:59
The problem in the demo is with the UART buffer and the sleep.  During the sleep, the sensor is filling up the buffer which is first in first out.  Based on a cursory read of the code, it looks like the buffer can hold over 100 entries.  Therefore, the actual heading getting printed in the demo can be old data.  

Your solution of resetting the buffer should work.  Another solution is to set the buffer to 19 bytes instead of 2048.
`uart = busio.UART(board.TX, board.RX, baudrate=115200, receiver_buffer_size=19)`
I chose 19 because the program looks for a 2-byte header prefix and then once found reads an additional 17 bytes which comprises the heading frame.

Obviously either approach has the potential to skip some of the transmitted 19-byte messages depending on how fast you process the received data.  Decreasing the sleep value should allow for a larger buffer.

**Comment by FoamyGuy** [comment] 2024-11-12 21:45
Closing this as the explanation above seems to provide the cause and a potential solution to the problem. Please feel free to re-open if still facing this issue.

**Closed as completed by FoamyGuy** 2024-11-12 21:45 UTC
